### ISSUE TITLE
Vue bug?

### ISSUE THREAD

**Issue by coldestheart** [oouo-diogo-perdigao/vscode-docthis#1]
Doesn't work for **.vue** components?

try to **Document this**,

```
methods: {
    clear() {
      this.clearData()
      this.$router.push('/wwwww')
      ......
      }
    }
```

and getting error

> Sorry! 'Document This' wasn't able to produce documentation at the current position.

**Comment by oouo-diogo-perdigao** [comment]
No, this extension work for only javascript functions.
